name: Build and Release Action

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Install dependencies
        run: npm install

      - name: Check status
        run: git status
      - name: Remove old index.js
        run: rm -fv action/index.js

      - name: Build
        run: npm run build

      - name: Check for changes in
        id: changes_check
        run: |
          git status
          lines_changed=$(git status -s | wc --lines)
          echo "has_changes=$lines_changed" >> $GITHUB_OUTPUT
          echo "Lines changed: $lines_changed"

      - name: Publish GitHub Action
        if: steps.changes_check.outputs.has_changes != '0'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Auto-build GitHub Action" &&
          git push origin main
